package npc

import (
	"database/sql"
	"fmt"
)

type NpcYaml struct {
	Npcs   []*Npc    `yaml:"npcs,omitempty"`
	Spawn2 []*Spawn2 `yaml:"spawn2,omitempty"`
}

type Npc struct {
	ID                   int            `yaml:"id,omitempty" db:"id"`                                         // int(11) NOT NULL AUTO_INCREMENT,
	Name                 string         `yaml:"name,omitempty" db:"name"`                                     // text NOT NULL,
	Lastname             sql.NullString `yaml:"lastname,omitempty" db:"lastname"`                             // varchar(32) DEFAULT NULL,
	Level                int            `yaml:"level,omitempty" db:"level"`                                   // tinyint(2) unsigned NOT NULL DEFAULT 0,
	Race                 int            `yaml:"race,omitempty" db:"race"`                                     // smallint(5) unsigned NOT NULL DEFAULT 0,
	Class                int            `yaml:"class,omitempty" db:"class"`                                   // tinyint(2) unsigned NOT NULL DEFAULT 0,
	Bodytype             int            `yaml:"bodytype,omitempty" db:"bodytype"`                             // int(11) NOT NULL DEFAULT 1,
	Hp                   int            `yaml:"hp,omitempty" db:"hp"`                                         // bigint(20) NOT NULL DEFAULT 0,
	Mana                 int            `yaml:"mana,omitempty" db:"mana"`                                     // bigint(20) NOT NULL DEFAULT 0,
	Gender               int            `yaml:"gender,omitempty" db:"gender"`                                 // tinyint(2) unsigned NOT NULL DEFAULT 0,
	Texture              int            `yaml:"texture,omitempty" db:"texture"`                               // tinyint(2) unsigned NOT NULL DEFAULT 0,
	Helmtexture          int            `yaml:"helmtexture,omitempty" db:"helmtexture"`                       // tinyint(2) unsigned NOT NULL DEFAULT 0,
	Herosforgemodel      int            `yaml:"herosforgemodel,omitempty" db:"herosforgemodel"`               // int(11) NOT NULL DEFAULT 0,
	Size                 float32        `yaml:"size,omitempty" db:"size"`                                     // float NOT NULL DEFAULT 0,
	HpRegenRate          int            `yaml:"hp_regen_rate,omitempty" db:"hp_regen_rate"`                   // bigint(20) NOT NULL DEFAULT 0,
	HpRegenPerSecond     int            `yaml:"hp_regen_per_second,omitempty" db:"hp_regen_per_second"`       // bigint(20) NOT NULL DEFAULT 0,
	ManaRegenRate        int            `yaml:"mana_regen_rate,omitempty" db:"mana_regen_rate"`               // bigint(20) NOT NULL DEFAULT 0,
	LoottableId          int            `yaml:"loottable_id,omitempty" db:"loottable_id"`                     // int(11) unsigned NOT NULL DEFAULT 0,
	MerchantId           int            `yaml:"merchant_id,omitempty" db:"merchant_id"`                       // int(11) unsigned NOT NULL DEFAULT 0,
	AltCurrencyId        int            `yaml:"alt_currency_id,omitempty" db:"alt_currency_id"`               // int(11) unsigned NOT NULL DEFAULT 0,
	NpcSpellsId          int            `yaml:"npc_spells_id,omitempty" db:"npc_spells_id"`                   // int(11) unsigned NOT NULL DEFAULT 0,
	NpcSpellsEffectsId   int            `yaml:"npc_spells_effects_id,omitempty" db:"npc_spells_effects_id"`   // int(11) unsigned NOT NULL DEFAULT 0,
	NpcFactionId         int            `yaml:"npc_faction_id,omitempty" db:"npc_faction_id"`                 // int(11) NOT NULL DEFAULT 0,
	AdventureTemplateId  int            `yaml:"adventure_template_id,omitempty" db:"adventure_template_id"`   // int(10) unsigned NOT NULL DEFAULT 0,
	TrapTemplate         int            `yaml:"trap_template,omitempty" db:"trap_template"`                   // int(10) unsigned DEFAULT 0,
	Mindmg               int            `yaml:"mindmg,omitempty" db:"mindmg"`                                 // int(10) unsigned NOT NULL DEFAULT 0,
	Maxdmg               int            `yaml:"maxdmg,omitempty" db:"maxdmg"`                                 // int(10) unsigned NOT NULL DEFAULT 0,
	AttackCount          int            `yaml:"attack_count,omitempty" db:"attack_count"`                     // smallint(6) NOT NULL DEFAULT -1,
	Npcspecialattks      string         `yaml:"npcspecialattks,omitempty" db:"npcspecialattks"`               // varchar(36) NOT NULL DEFAULT '',
	SpecialAbilities     sql.NullString `yaml:"special_abilities,omitempty" db:"special_abilities"`           // text DEFAULT NULL,
	Aggroradius          int            `yaml:"aggroradius,omitempty" db:"aggroradius"`                       // int(10) unsigned NOT NULL DEFAULT 0,
	Assistradius         int            `yaml:"assistradius,omitempty" db:"assistradius"`                     // int(10) unsigned NOT NULL DEFAULT 0,
	Face                 int            `yaml:"face,omitempty" db:"face"`                                     // int(10) unsigned NOT NULL DEFAULT 1,
	LuclinHairstyle      int            `yaml:"luclin_hairstyle,omitempty" db:"luclin_hairstyle"`             // int(10) unsigned NOT NULL DEFAULT 1,
	LuclinHaircolor      int            `yaml:"luclin_haircolor,omitempty" db:"luclin_haircolor"`             // int(10) unsigned NOT NULL DEFAULT 1,
	LuclinEyecolor       int            `yaml:"luclin_eyecolor,omitempty" db:"luclin_eyecolor"`               // int(10) unsigned NOT NULL DEFAULT 1,
	LuclinEyecolor2      int            `yaml:"luclin_eyecolor2,omitempty" db:"luclin_eyecolor2"`             // int(10) unsigned NOT NULL DEFAULT 1,
	LuclinBeardcolor     int            `yaml:"luclin_beardcolor,omitempty" db:"luclin_beardcolor"`           // int(10) unsigned NOT NULL DEFAULT 1,
	LuclinBeard          int            `yaml:"luclin_beard,omitempty" db:"luclin_beard"`                     // int(10) unsigned NOT NULL DEFAULT 0,
	DrakkinHeritage      int            `yaml:"drakkin_heritage,omitempty" db:"drakkin_heritage"`             // int(10) NOT NULL DEFAULT 0,
	DrakkinTattoo        int            `yaml:"drakkin_tattoo,omitempty" db:"drakkin_tattoo"`                 // int(10) NOT NULL DEFAULT 0,
	DrakkinDetails       int            `yaml:"drakkin_details,omitempty" db:"drakkin_details"`               // int(10) NOT NULL DEFAULT 0,
	ArmortintId          int            `yaml:"armortint_id,omitempty" db:"armortint_id"`                     // int(10) unsigned NOT NULL DEFAULT 0,
	ArmortintRed         int            `yaml:"armortint_red,omitempty" db:"armortint_red"`                   // tinyint(3) unsigned NOT NULL DEFAULT 0,
	ArmortintGreen       int            `yaml:"armortint_green,omitempty" db:"armortint_green"`               // tinyint(3) unsigned NOT NULL DEFAULT 0,
	ArmortintBlue        int            `yaml:"armortint_blue,omitempty" db:"armortint_blue"`                 // tinyint(3) unsigned NOT NULL DEFAULT 0,
	DMeleeTexture1       int            `yaml:"d_melee_texture1,omitempty" db:"d_melee_texture1"`             // int(11) NOT NULL DEFAULT 0,
	DMeleeTexture2       int            `yaml:"d_melee_texture2,omitempty" db:"d_melee_texture2"`             // int(11) NOT NULL DEFAULT 0,
	AmmoIdfile           string         `yaml:"ammo_idfile,omitempty" db:"ammo_idfile"`                       // varchar(30) NOT NULL DEFAULT 'IT10',
	PrimMeleeType        int            `yaml:"prim_melee_type,omitempty" db:"prim_melee_type"`               // tinyint(4) unsigned NOT NULL DEFAULT 28,
	SecMeleeType         int            `yaml:"sec_melee_type,omitempty" db:"sec_melee_type"`                 // tinyint(4) unsigned NOT NULL DEFAULT 28,
	RangedType           int            `yaml:"ranged_type,omitempty" db:"ranged_type"`                       // tinyint(4) unsigned NOT NULL DEFAULT 7,
	Runspeed             float32        `yaml:"runspeed,omitempty" db:"runspeed"`                             // float NOT NULL DEFAULT 0,
	MR                   int            `yaml:"MR,omitempty" db:"MR"`                                         // smallint(5) NOT NULL DEFAULT 0,
	CR                   int            `yaml:"CR,omitempty" db:"CR"`                                         // smallint(5) NOT NULL DEFAULT 0,
	DR                   int            `yaml:"DR,omitempty" db:"DR"`                                         // smallint(5) NOT NULL DEFAULT 0,
	FR                   int            `yaml:"FR,omitempty" db:"FR"`                                         // smallint(5) NOT NULL DEFAULT 0,
	PR                   int            `yaml:"PR,omitempty" db:"PR"`                                         // smallint(5) NOT NULL DEFAULT 0,
	Corrup               int            `yaml:"Corrup,omitempty" db:"Corrup"`                                 // smallint(5) NOT NULL DEFAULT 0,
	PhR                  int            `yaml:"PhR,omitempty" db:"PhR"`                                       // smallint(5) unsigned NOT NULL DEFAULT 0,
	SeeInvis             int            `yaml:"see_invis,omitempty" db:"see_invis"`                           // smallint(4) NOT NULL DEFAULT 0,
	SeeInvisUndead       int            `yaml:"see_invis_undead,omitempty" db:"see_invis_undead"`             // smallint(4) NOT NULL DEFAULT 0,
	Qglobal              int            `yaml:"qglobal,omitempty" db:"qglobal"`                               // int(2) unsigned NOT NULL DEFAULT 0,
	AC                   int            `yaml:"AC,omitempty" db:"AC"`                                         // smallint(5) NOT NULL DEFAULT 0,
	NpcAggro             int            `yaml:"npc_aggro,omitempty" db:"npc_aggro"`                           // tinyint(4) NOT NULL DEFAULT 0,
	SpawnLimit           int            `yaml:"spawn_limit,omitempty" db:"spawn_limit"`                       // tinyint(4) NOT NULL DEFAULT 0,
	AttackSpeed          float32        `yaml:"attack_speed,omitempty" db:"attack_speed"`                     // float NOT NULL DEFAULT 0,
	AttackDelay          int            `yaml:"attack_delay,omitempty" db:"attack_delay"`                     // tinyint(3) unsigned NOT NULL DEFAULT 30,
	Findable             int            `yaml:"findable,omitempty" db:"findable"`                             // tinyint(4) NOT NULL DEFAULT 0,
	STR                  int            `yaml:"STR,omitempty" db:"STR"`                                       // mediumint(8) unsigned NOT NULL DEFAULT 75,
	STA                  int            `yaml:"STA,omitempty" db:"STA"`                                       // mediumint(8) unsigned NOT NULL DEFAULT 75,
	DEX                  int            `yaml:"DEX,omitempty" db:"DEX"`                                       // mediumint(8) unsigned NOT NULL DEFAULT 75,
	AGI                  int            `yaml:"AGI,omitempty" db:"AGI"`                                       // mediumint(8) unsigned NOT NULL DEFAULT 75,
	INT                  int            `yaml:"_INT,omitempty" db:"_INT"`                                     // mediumint(8) unsigned NOT NULL DEFAULT 80,
	WIS                  int            `yaml:"WIS,omitempty" db:"WIS"`                                       // mediumint(8) unsigned NOT NULL DEFAULT 75,
	CHA                  int            `yaml:"CHA,omitempty" db:"CHA"`                                       // mediumint(8) unsigned NOT NULL DEFAULT 75,
	SeeHide              int            `yaml:"see_hide,omitempty" db:"see_hide"`                             // tinyint(4) NOT NULL DEFAULT 0,
	SeeImprovedHide      int            `yaml:"see_improved_hide,omitempty" db:"see_improved_hide"`           // tinyint(4) NOT NULL DEFAULT 0,
	Trackable            int            `yaml:"trackable,omitempty" db:"trackable"`                           // tinyint(4) NOT NULL DEFAULT 1,
	Isbot                int            `yaml:"isbot,omitempty" db:"isbot"`                                   // tinyint(4) NOT NULL DEFAULT 0,
	Exclude              int            `yaml:"exclude,omitempty" db:"exclude"`                               // tinyint(4) NOT NULL DEFAULT 1,
	ATK                  int            `yaml:"ATK,omitempty" db:"ATK"`                                       // mediumint(9) NOT NULL DEFAULT 0,
	Accuracy             int            `yaml:"Accuracy,omitempty" db:"Accuracy"`                             // mediumint(9) NOT NULL DEFAULT 0,
	Avoidance            int            `yaml:"Avoidance,omitempty" db:"Avoidance"`                           // mediumint(9) unsigned NOT NULL DEFAULT 0,
	SlowMitigation       int            `yaml:"slow_mitigation,omitempty" db:"slow_mitigation"`               // smallint(4) NOT NULL DEFAULT 0,
	Version              int            `yaml:"version,omitempty" db:"version"`                               // smallint(5) unsigned NOT NULL DEFAULT 0,
	Maxlevel             int            `yaml:"maxlevel,omitempty" db:"maxlevel"`                             // tinyint(3) NOT NULL DEFAULT 0,
	Scalerate            int            `yaml:"scalerate,omitempty" db:"scalerate"`                           // int(11) NOT NULL DEFAULT 100,
	PrivateCorpse        int            `yaml:"private_corpse,omitempty" db:"private_corpse"`                 // tinyint(3) unsigned NOT NULL DEFAULT 0,
	UniqueSpawnByName    int            `yaml:"unique_spawn_by_name,omitempty" db:"unique_spawn_by_name"`     // tinyint(3) unsigned NOT NULL DEFAULT 0,
	Underwater           int            `yaml:"underwater,omitempty" db:"underwater"`                         // tinyint(3) unsigned NOT NULL DEFAULT 0,
	Isquest              int            `yaml:"isquest,omitempty" db:"isquest"`                               // tinyint(3) NOT NULL DEFAULT 0,
	Emoteid              int            `yaml:"emoteid,omitempty" db:"emoteid"`                               // int(10) unsigned NOT NULL DEFAULT 0,
	Spellscale           float32        `yaml:"spellscale,omitempty" db:"spellscale"`                         // float NOT NULL DEFAULT 100,
	Healscale            float32        `yaml:"healscale,omitempty" db:"healscale"`                           // float NOT NULL DEFAULT 100,
	NoTargetHotkey       int            `yaml:"no_target_hotkey,omitempty" db:"no_target_hotkey"`             // tinyint(1) unsigned NOT NULL DEFAULT 0,
	RaidTarget           int            `yaml:"raid_target,omitempty" db:"raid_target"`                       // tinyint(1) unsigned NOT NULL DEFAULT 0,
	Armtexture           int            `yaml:"armtexture,omitempty" db:"armtexture"`                         // tinyint(2) NOT NULL DEFAULT 0,
	Bracertexture        int            `yaml:"bracertexture,omitempty" db:"bracertexture"`                   // tinyint(2) NOT NULL DEFAULT 0,
	Handtexture          int            `yaml:"handtexture,omitempty" db:"handtexture"`                       // tinyint(2) NOT NULL DEFAULT 0,
	Legtexture           int            `yaml:"legtexture,omitempty" db:"legtexture"`                         // tinyint(2) NOT NULL DEFAULT 0,
	Feettexture          int            `yaml:"feettexture,omitempty" db:"feettexture"`                       // tinyint(2) NOT NULL DEFAULT 0,
	Light                int            `yaml:"light,omitempty" db:"light"`                                   // tinyint(2) NOT NULL DEFAULT 0,
	Walkspeed            int            `yaml:"walkspeed,omitempty" db:"walkspeed"`                           // tinyint(2) NOT NULL DEFAULT 0,
	Peqid                int            `yaml:"peqid,omitempty" db:"peqid"`                                   // int(11) NOT NULL DEFAULT 0,
	Unique               int            `yaml:"unique_,omitempty" db:"unique_"`                               // tinyint(2) NOT NULL DEFAULT 0,
	Fixed                int            `yaml:"fixed,omitempty" db:"fixed"`                                   // tinyint(2) NOT NULL DEFAULT 0,
	IgnoreDespawn        int            `yaml:"ignore_despawn,omitempty" db:"ignore_despawn"`                 // tinyint(2) NOT NULL DEFAULT 0,
	ShowName             int            `yaml:"show_name,omitempty" db:"show_name"`                           // tinyint(2) NOT NULL DEFAULT 1,
	Untargetable         int            `yaml:"untargetable,omitempty" db:"untargetable"`                     // tinyint(2) NOT NULL DEFAULT 0,
	CharmAc              int            `yaml:"charm_ac,omitempty" db:"charm_ac"`                             // smallint(5) DEFAULT 0,
	CharmMinDmg          int            `yaml:"charm_min_dmg,omitempty" db:"charm_min_dmg"`                   // int(10) DEFAULT 0,
	CharmMaxDmg          int            `yaml:"charm_max_dmg,omitempty" db:"charm_max_dmg"`                   // int(10) DEFAULT 0,
	CharmAttackDelay     int            `yaml:"charm_attack_delay,omitempty" db:"charm_attack_delay"`         // tinyint(3) DEFAULT 0,
	CharmAccuracyRating  int            `yaml:"charm_accuracy_rating,omitempty" db:"charm_accuracy_rating"`   // mediumint(9) DEFAULT 0,
	CharmAvoidanceRating int            `yaml:"charm_avoidance_rating,omitempty" db:"charm_avoidance_rating"` // mediumint(9) DEFAULT 0,
	CharmAtk             int            `yaml:"charm_atk,omitempty" db:"charm_atk"`                           // mediumint(9) DEFAULT 0,
	SkipGlobalLoot       int            `yaml:"skip_global_loot,omitempty" db:"skip_global_loot"`             // tinyint(4) DEFAULT 0,
	RareSpawn            int            `yaml:"rare_spawn,omitempty" db:"rare_spawn"`                         // tinyint(4) DEFAULT 0,
	StuckBehavior        int            `yaml:"stuck_behavior,omitempty" db:"stuck_behavior"`                 // tinyint(4) NOT NULL DEFAULT 0,
	Model                int            `yaml:"model,omitempty" db:"model"`                                   // smallint(5) NOT NULL DEFAULT 0,
	Flymode              int            `yaml:"flymode,omitempty" db:"flymode"`                               // tinyint(4) NOT NULL DEFAULT -1,
	AlwaysAggro          int            `yaml:"always_aggro,omitempty" db:"always_aggro"`                     // tinyint(1) NOT NULL DEFAULT 0,
	ExpMod               int            `yaml:"exp_mod,omitempty" db:"exp_mod"`                               // int(11) NOT NULL DEFAULT 100,
	HeroicStrikethrough  int            `yaml:"heroic_strikethrough,omitempty" db:"heroic_strikethrough"`     // int(11) NOT NULL DEFAULT 0,
	FactionAmount        int            `yaml:"faction_amount,omitempty" db:"faction_amount"`                 // int(10) NOT NULL DEFAULT 0,
	KeepsSoldItems       int            `yaml:"keeps_sold_items,omitempty" db:"keeps_sold_items"`             // tinyint(1) unsigned NOT NULL DEFAULT 1,
	Spawns               []*Spawn       `yaml:"spawn,omitempty"`
}

// Spawn is SpawnEntry
type Spawn struct {
	SpawngroupID         int            `yaml:"spawngroupID,omitempty" db:"spawngroupID"`                     // int(11) NOT NULL DEFAULT 0,
	NpcID                int            `yaml:"npcID,omitempty" db:"npcID"`                                   // int(11) NOT NULL DEFAULT 0,
	Chance               int            `yaml:"chance,omitempty" db:"chance"`                                 // smallint(4) NOT NULL DEFAULT 0,
	ConditionValueFilter int            `yaml:"condition_value_filter,omitempty" db:"condition_value_filter"` // mediumint(9) NOT NULL DEFAULT 1,
	MinExpansion         int            `yaml:"min_expansion,omitempty" db:"min_expansion"`                   // tinyint(4) NOT NULL DEFAULT -1,
	MaxExpansion         int            `yaml:"max_expansion,omitempty" db:"max_expansion"`                   // tinyint(4) NOT NULL DEFAULT -1,
	ContentFlags         sql.NullString `yaml:"content_flags,omitempty" db:"content_flags"`                   // varchar(100) DEFAULT NULL,
	ContentFlagsDisabled sql.NullString `yaml:"content_flags_disabled,omitempty" db:"content_flags_disabled"` // varchar(100) DEFAULT NULL,
	Id                   int            `yaml:"id,omitempty" db:"id"`                                         // int(11) NOT NULL AUTO_INCREMENT,
	Name                 string         `yaml:"name,omitempty" db:"name"`                                     // varchar(50) NOT NULL DEFAULT '',
	SpawnLimit           int            `yaml:"spawn_limit,omitempty" db:"spawn_limit"`                       // tinyint(4) NOT NULL DEFAULT 0,
	Dist                 float32        `yaml:"dist,omitempty" db:"dist"`                                     // float NOT NULL DEFAULT 0,
	MaxX                 float32        `yaml:"max_x,omitempty" db:"max_x"`                                   // float NOT NULL DEFAULT 0,
	MinX                 float32        `yaml:"min_x,omitempty" db:"min_x"`                                   // float NOT NULL DEFAULT 0,
	MaxY                 float32        `yaml:"max_y,omitempty" db:"max_y"`                                   // float NOT NULL DEFAULT 0,
	MinY                 float32        `yaml:"min_y,omitempty" db:"min_y"`                                   // float NOT NULL DEFAULT 0,
	Delay                int            `yaml:"delay,omitempty" db:"delay"`                                   // int(11) NOT NULL DEFAULT 45000,
	Mindelay             int            `yaml:"mindelay,omitempty" db:"mindelay"`                             // int(11) NOT NULL DEFAULT 15000,
	Despawn              int            `yaml:"despawn,omitempty" db:"despawn"`                               // tinyint(3) NOT NULL DEFAULT 0,
	DespawnTimer         int            `yaml:"despawn_timer,omitempty" db:"despawn_timer"`                   // int(11) NOT NULL DEFAULT 100,
	WpSpawns             int            `yaml:"wp_spawns,omitempty" db:"wp_spawns"`                           // tinyint(1) unsigned NOT NULL DEFAULT 0,
}

type Spawn2 struct {
	ID                   int            `yaml:"id" db:"id"`                                         // int(11) NOT NULL AUTO_INCREMENT,
	SpawngroupID         int            `yaml:"spawngroupID" db:"spawngroupID"`                     // int(11) NOT NULL DEFAULT 0,
	Zone                 sql.NullString `yaml:"zone" db:"zone"`                                     // varchar(32) DEFAULT NULL,
	Version              int            `yaml:"version" db:"version"`                               // smallint(5) NOT NULL DEFAULT 0,
	X                    float32        `yaml:"spawn_x" db:"x"`                                     // float(14,6) NOT NULL DEFAULT 0.000000,
	Y                    float32        `yaml:"spawn_y" db:"y"`                                     // float(14,6) NOT NULL DEFAULT 0.000000,
	Z                    float32        `yaml:"spawn_z" db:"z"`                                     // float(14,6) NOT NULL DEFAULT 0.000000,
	Heading              float32        `yaml:"heading" db:"heading"`                               // float(14,6) NOT NULL DEFAULT 0.000000,
	Respawntime          int            `yaml:"respawntime" db:"respawntime"`                       // int(11) NOT NULL DEFAULT 0,
	Variance             int            `yaml:"variance" db:"variance"`                             // int(11) NOT NULL DEFAULT 0,
	Pathgrid             int            `yaml:"pathgrid" db:"pathgrid"`                             // int(10) NOT NULL DEFAULT 0,
	PathWhenZoneIdle     int            `yaml:"path_when_zone_idle" db:"path_when_zone_idle"`       // tinyint(1) NOT NULL DEFAULT 0,
	Condition            int            `yaml:"_condition" db:"_condition"`                         // mediumint(8) unsigned NOT NULL DEFAULT 0,
	CondValue            int            `yaml:"cond_value" db:"cond_value"`                         // mediumint(9) NOT NULL DEFAULT 1,
	Enabled              int            `yaml:"enabled" db:"enabled"`                               // tinyint(3) unsigned NOT NULL DEFAULT 1,
	Animation            int            `yaml:"animation" db:"animation"`                           // tinyint(3) unsigned NOT NULL DEFAULT 0,
	MinExpansion         int            `yaml:"min_expansion" db:"min_expansion"`                   // tinyint(4) NOT NULL DEFAULT -1,
	MaxExpansion         int            `yaml:"max_expansion" db:"max_expansion"`                   // tinyint(4) NOT NULL DEFAULT -1,
	ContentFlags         sql.NullString `yaml:"content_flags" db:"content_flags"`                   // varchar(100) DEFAULT NULL,
	ContentFlagsDisabled sql.NullString `yaml:"content_flags_disabled" db:"content_flags_disabled"` // varchar(100) DEFAULT NULL,
}

func (e *NpcYaml) sanitize() error {
	for _, npc := range e.Npcs {
		if npc.Name == "" {
			return fmt.Errorf("npc name must not be empty")
		}
	}
	return nil
}
